### ISSUE TITLE
どうやってインストールしますか？

### ISSUE THREAD

**Issue by ywatanabe1989** [korita1995/PubmedSearch#1]
![image](https://user-images.githubusercontent.com/42527473/89723140-5dc81a80-da2d-11ea-826d-804d2adb1225.png)
私の Windows 環境 (特にほぼ何も開発に必要なものをインストールしていない) では、PubmedSearch2FileName.exe ファイルをダブルクリックしただけでは何も動作しないという状態でした。

より具体的には、Window が立ち上がらず、下のタスクバーにアプリケーションが起動している形跡？がありました。
![image](https://user-images.githubusercontent.com/42527473/89723145-6d476380-da2d-11ea-8e31-042ad9f00f6c.png)

・Visual studio 2019 でビルド
・C++ 用のJSONライブラリの導入
・その他の必要事項（リンカー？）
などがやはり関係あるのでしょうか。

ぜひ使ってみたいので、よかったらお時間ある時にでも教えて下さい！

**Comment by korita1995** [comment]
ご連絡ありがとうございます。
再起動時に描画位置の復元を行うという処理を入れているのですが、その部分に問題があったようです。
明日から3日間の登校禁止期間中に修正しますので、少々お待ちください！

**Comment by ywatanabe1989** [comment]
なるほど、”投稿” は禁止ではない、と。笑
ご自身のペースで、もしできたタイミングで私が素人の利用者としてチェックさせてもらいますね！
そうしたら、他の人も使ってみよう！ってなるので！

私はただ、PubmedSearchApp.cpp や Resource.rc なんかを見て、皆のために、かなり丁寧に作ったのだな、とか、Git / GitHub を使いこなしていて、さすがだなあ、とコメントしてしまいました～！(わからずに修正の Pull Request できなくてごめんなさい笑)

**Comment by korita1995** [comment]
時間がかかってしまい大変申し訳ございませんでしたが、恐らく問題解決できたと思われます。
お時間のある時にお試しいただけますと幸いです。
よろしくお願いいたします。

**Comment by ywatanabe1989** [comment]
クリップボード、ボタンのサイズ感、アイコンまでバッチリですね...！！
タスクバーに常駐させて貰います、ありがとうございます！m(_ _)m
